Khata_Register/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='khata')),
    path('users/',include('user_app.urls')),
    path('',include('customer_app.urls',namespace='customer')),
    path('about/',views.about,name='about'),
    path('previous_url',views.previous_url,name='previous_url'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
app_name = 'khata'
urlpatterns = [
    path('<int:id>/<str:name>/',views.show_account,name='account'),
    path('gave/',views.Gave.as_view(),name='gave'),
    path('update_gave/<int:pk>/<int:cust_id>/',views.Update_Gave.as_view(),name='update_gave'),
    path('got/',views.Got.as_view(),name='got'),
    path('update_got/<int:pk>/<int:cust_id>/',views.Update_Got.as_view(),name='update_got'),
    path('delete_account/<int:pk>/',views.Delete_Account.as_view(),name='delete_account'),

]

customer_app/urls.py
from django.urls import path
from . import views
app_name = 'customer'
urlpatterns = [
    path('',views.show_customer,name='show_customer'),
    path('<int:id>/',views.show_customer,name='show_customer'),
    path('add_customer/',views.Add_Customer.as_view(),name='add_customer'),
    path('update_customer/<int:pk>/',views.Update_Customer.as_view(),name='update_customer'),
    path('delete_customer/<int:pk>/',views.Delete_Customer.as_view(),name='delete_customer'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from customer_app.models import Customer
from django.core import validators

class Account(models.Model):
    def validate_amount(val):
        if val < 1:
            raise validators.ValidationError('Amount should be atleast 1')

    customer = models.ForeignKey(Customer,on_delete=models.CASCADE,blank=True,null=True,related_name='account')
    desc = models.CharField(max_length=100)
    gave = models.IntegerField(default=0,validators=[validate_amount])
    got = models.IntegerField(default=0,validators=[validate_amount])
    created_at = models.DateTimeField(auto_now_add=True)

    objects = models.Manager
    
    def __str__(self):
        return self.desc

accounts/forms.py
from .models import Account
from django import forms


class GaveForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('desc','gave','customer')
        widgets = {
            'desc':forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Enter Description',
                'autofocus':'True',
                'tabindex':'1',
            }),
            'gave':forms.NumberInput(attrs={
                'class':'form-control',
                'placeholder':'Enter Amount you gave',
                'tabindex':'2',
            })
        }

class GotForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('desc','got','customer')
        widgets = {
            'desc':forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Enter Description',
                'tabindex':'1',
            }),
            'got':forms.NumberInput(attrs={
                'class':'form-control',
                'placeholder':'Enter Amount you got',
                'tabindex':'2',
            })
        }

accounts/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Account
from customer_app.models import Customer
from .forms import GaveForm,GotForm
from django.views.generic import CreateView,UpdateView,DeleteView,DetailView

# To Calculate Selected Customer Balance Amount to be given or to be taken.
def cust_balance(request,id):
    cust_queryset = Account.objects.filter(customer__user=request.user, customer=id)
    got,gave = 0,0
    for i in cust_queryset:
        got = got + i.got
        gave = gave + i.gave
        balance = gave - got
    try:
        return balance
    except:
        return 0

@login_required(login_url='/users/signin')
def show_account(request,id,name):
    cust_id =id
    cust_name = name
    cust_bal = cust_balance(request,id)
    entries = Account.objects.filter(customer=id)
    # Session
    request.session['previous_url'] = request.path
    context = {'cust_name':cust_name, 'cust_id':cust_id,
                'entries':entries,'balance':cust_bal}
    return render(request, 'accounts/show_account.html', context)

class Gave(CreateView):
    form_class = GaveForm
    template_name = 'accounts/gave.html'
    success_url = '/customer/'

    def form_valid(self,form):
        cust_id = self.request.GET.get('cust_id')
        form.instance.customer = Customer.objects.get(id=cust_id)
        return super().form_valid(form)

    def get_success_url(self):
        success = self.request.session['previous_url']
        return success
    
    def get_context_data(self, **kwargs):
        context = super(Gave, self).get_context_data(**kwargs)
        context['previous_url'] = self.request.session['previous_url']
        return context


class Update_Gave(UpdateView):
    form_class = GaveForm
    template_name = 'accounts/update_gave.html'
    success_url = '/customer/'

    def form_valid(self,form):
        # cust_id = self.request.GET.get('cust_id')
        cust_id = self.kwargs['cust_id']
        form.instance.customer = Customer.objects.get(id=cust_id)
        return super().form_valid(form)

    def get_queryset(self):
        pk = self.kwargs['pk']
        return Account.objects.filter(pk=pk)
    
    def get_success_url(self):
        success = self.request.session['previous_url']
        return success

    def get_context_data(self, **kwargs):
        self.request.session['previous_url_del_acc'] = self.request.path
        context = super(Update_Gave, self).get_context_data(**kwargs)
        account_pk = self.kwargs['pk']
        print(account_pk)
        context['previous_url'] = self.request.session['previous_url']
        context['account_pk'] = account_pk
        return context

class Got(CreateView):
    form_class = GotForm
    template_name = 'accounts/got.html'
    success_url = '/customer/'

    def form_valid(self,form):
        cust_id = self.request.GET.get('cust_id')
        form.instance.customer = Customer.objects.get(id=cust_id)
        return super().form_valid(form)
    
    def get_success_url(self):
        success = self.request.session['previous_url']
        return success
    
    def get_context_data(self, **kwargs):
        context = super(Got, self).get_context_data(**kwargs)
        context['previous_url'] = self.request.session['previous_url']
        return context

class Update_Got(UpdateView):
    form_class = GotForm
    template_name = 'accounts/update_got.html'
    success_url = '/customer/'

    def form_valid(self,form):
        # cust_id = self.request.GET.get('cust_id')
        cust_id = self.kwargs['cust_id']
        form.instance.customer = Customer.objects.get(id=cust_id)
        return super().form_valid(form)

    def get_queryset(self):
        pk = self.kwargs['pk']
        return Account.objects.filter(pk=pk)
    
    def get_success_url(self):
        success = self.request.session['previous_url']
        return success

    def get_context_data(self, **kwargs):
        self.request.session['previous_url_del_acc'] = self.request.path
        context = super(Update_Got, self).get_context_data(**kwargs)
        account_pk = self.kwargs['pk']
        print(account_pk)
        context['previous_url'] = self.request.session['previous_url']
        context['account_pk'] = account_pk
        return context

class Delete_Account(DeleteView):
    model = Account
    success_url = '/customer'

    def get_success_url(self):
        success = self.request.session['previous_url']
        return success

    def get_context_data(self, **kwargs):
        context = super(Delete_Account, self).get_context_data(**kwargs)
        context['previous_url_del_acc'] = self.request.session['previous_url_del_acc']
        return context










































# @login_required(login_url='/users/signin')
# def gave(request):
#     print(id)
#     form = GaveForm()
#     if request.method == 'POST':
#         form = GaveForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('/customer/')
#         else:
#             return render(request,'accounts/gave.html',{'form':form})
#     return render(request,'accounts/gave.html',{'form':form})

# @login_required(login_url='/users/signin')
# def got(request):
#     forms = GotForm()
#     if request.method == 'POST':
#         forms = GotForm(request.POST)
#         if forms.is_valid():
#             forms.save()
#             return redirect('/customer/')
#         else:
#             return render(request,'accounts/gave.html',{'forms':forms})
#     return render(request,'accounts/got.html',{'forms':forms})

templates/accounts/account_confirm_delete.html
{% extends 'layout_app.html' %}
{% block content %}
{% load static %}
<!doctype html>
<html lang="en">
<html>

<head>
    <link rel="stylesheet" href="{% static 'css/style_customer.css' %}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border border-info rounded-right">
        <h4>
            <a href="{{previous_url_del_acc}}" class="btn btn-secondary">
                << </a>
                    <label style="color: blanchedalmond;">Delete Transaction</label>
        </h4>
    </nav>
    <!-- Navbar ends -->
    <br><br>
    <form class="form-row" method="POST">
        {% csrf_token %}
        <div align="center" class="col-md-4 order-md-1">
            <h5>Delete Transaction</h5>
            <hr><label><small>This will delete selected Transaction.</small></label><hr>
            <input type="submit" value="Delete" class="btn btn-danger"><br><br>
            <a class="btn btn-primary" href="{{previous_url_del_acc}}">Cancel</a>
    </form>

    {% endblock %}

templates/accounts/gave.html
{% extends 'layout_app.html' %}
{% block content %}
{% load static %}
<!doctype html>
<html lang="en">
<html>

<head>
    <link rel="stylesheet" href="{% static 'css/style_account.css' %}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border border-info rounded-right">
        <h4>
            <a href="{{previous_url}}" class="btn btn-secondary">
                << </a>
                    <label style="color: blanchedalmond;">You Gave</label>
        </h4>
    </nav>
    <!-- Navbar ends -->
<br><br>

<form class="form-row" method="POST">
    {% csrf_token %}
    <div align="center" class="col-md-4 order-md-1">
    <label>Description:</label> {{form.desc}}<br>
    <label>Amount gave:</label> {{form.gave}}<br>
    <input type="submit" value="You Gave" class="btn btn-outline-primary">
    </div>
</form>

{% if form.errors %}
    {% for error in form %}
        {% for err in error.errors %}
            <div class="alert alert-danger">
                <strong>{{ err|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% endblock %}

templates/accounts/got.html
{% extends 'layout_app.html' %}
{% block content %}
{% load static %}
<!doctype html>
<html lang="en">
<html>

<head>
    <link rel="stylesheet" href="{% static 'css/style_account.css' %}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border border-info rounded-right">
        <h4>
            <a href="{{previous_url}}" class="btn btn-secondary">
                << </a>
                    <label style="color: blanchedalmond;">You Got</label>
        </h4>
    </nav>
    <!-- Navbar ends -->
<br><br>

<form class="form-row" method="POST">
    {% csrf_token %}
    <div align="center" class="col-md-4 order-md-1">
    <label>Description:</label> {{form.desc}}<br>
    <label>Amount gave:</label> {{form.got}}<br>
    <input type="submit" value="You Got" class="btn btn-outline-primary">
    </div>
</form>

{% if form.errors %}
    {% for error in form %}
        {% for err in error.errors %}
            <div class="alert alert-danger">
                <strong>{{ err|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% endblock %}

templates/accounts/show_account.html
{% extends 'layout_app.html' %}
{% block content %}
{% load mathfilters %}

<head>
    <style>
        #table {
            font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }
        #table td,
        #table th {
            border: 1px solid #ddd;
            padding: 8px;
        }
        #table td a{
            color: black;
            
        }
        #table tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        #table tr:hover {
            background-color: #ddd;
        }
        #table th {
            padding-top: 3px;
            padding-bottom: 3px;
            text-align: center;
            background-color: rgb(255, 255, 255);
            color: rgb(110, 103, 103);
            font-size:x-small;
        }
    </style>
</head>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border border-info rounded-right">
    <h4>
        <a href="{% url 'customer:show_customer' %}" class="btn btn-secondary"><<</a>
        <a style="color: blanchedalmond;" href="{% url 'customer:update_customer' pk=cust_id %}">{{cust_name}}'s
            Account</a>
    </h4>
</nav>
<!-- Navbar ends -->

<div class="row mb-4" align="center">
    {% if balance > 0  %}
    <div class="col-6 themed-grid-col" style="color: green;border:solid;">{{balance}}<br><small>You will receive</small>
    </div>
    <div class="col-6 themed-grid-col" style="color: red;border:solid;">0<br><small>You will pay</small></div>
    {% elif balance == 0 %}
    <div class="col-6 themed-grid-col" style="color: green;border:solid;">0<br><small>You will receive</small></div>
    <div class="col-6 themed-grid-col" style="color: red;border:solid;">0<br><small>You will pay</small></div>
    {% else %}
    <div class="col-6 themed-grid-col" style="color: green;border:solid;">0<br><small>You will receive</small></div>
    <div class="col-6 themed-grid-col" style="color: red;border:solid;">{{balance | abs}}<br><small>You will
            pay</small></div>
    {% endif %}
</div>

<table id="table">
    <tr>
        <th>ENTRIES</th>
        <th>YOU GAVE</th>
        <th>YOU GOT</th>
    </tr>
    {% for entry in entries %}
    <tr>
        {% if entry.gave > entry.got %}
        <td><a href="{% url 'khata:update_gave' pk=entry.pk cust_id=cust_id %}"
                class="link">{{entry.desc}}<br><small>{{entry.created_at}}</small></td></a>
        <td style="color: red;">{{entry.gave}}</td>
        <td></td>
        {% else %}
        <td><a href="{% url 'khata:update_got' pk=entry.pk cust_id=cust_id %}"
                class="link">{{entry.desc}}<br><small>{{entry.created_at}}</small></td></a>
        <td></td>
        <td style="color: green;">{{entry.got}}</td>
        {% endif %}
        
    </tr>
    {% endfor %}
</table>

<br><br>
    <div style="position: fixed;bottom: 0;width: 100%;">
   <label></label>
    <a href="{% url 'khata:gave' %}?cust_id={{cust_id}}" class="btn btn-danger">You Gave</a>
    <a href="{% url 'khata:got' %}?cust_id={{cust_id}}" class="btn btn-success">You Got</a>
    
    </div>
{% endblock %}

templates/accounts/update_gave.html
{% extends 'layout_app.html' %}
{% block content %}
{% load static %}
<!doctype html>
<html lang="en">
<html>

<head>
    <link rel="stylesheet" href="{% static 'css/style_account.css' %}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border border-info rounded-right">
        <h4>
            <a href="{{previous_url}}" class="btn btn-secondary">
                << </a>
                    <label style="color: blanchedalmond;">Update You Gave</label>
        </h4>
    </nav>
    <!-- Navbar ends -->
<br><br>

<form class="form-row" method="POST">
    {% csrf_token %}
    <div align="center" class="col-md-4 order-md-1">
    <label>Description:</label> {{form.desc}}<br>
    <label>Amount gave:</label> {{form.gave}}<br>
    <input type="submit" value="Update Gave" class="btn btn-outline-primary"><br><br>
    <a href="{% url 'khata:delete_account' pk=account_pk %}" class="btn btn-outline-danger">Delete Transaction</a>
    </div>
</form>

{% if form.errors %}
    {% for error in form %}
        {% for err in error.errors %}
            <div class="alert alert-danger">
                <strong>{{ err|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% endblock %}

templates/accounts/update_got.html
{% extends 'layout_app.html' %}
{% block content %}
{% load static %}
<!doctype html>
<html lang="en">
<html>

<head>
    <link rel="stylesheet" href="{% static 'css/style_account.css' %}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border border-info rounded-right">
        <h4>
            <a href="{{previous_url}}" class="btn btn-secondary">
                << </a>
                    <label style="color: blanchedalmond;">Update You Got</label>
        </h4>
    </nav>
    <!-- Navbar ends -->
<br><br>

<form class="form-row" method="POST">
    {% csrf_token %}
    <div align="center" class="col-md-4 order-md-1">
    <label>Description:</label> {{form.desc}}<br>
    <label>Amount gave:</label> {{form.got}}<br>
    <input type="submit" value="Update Got" class="btn btn-outline-primary"><br><br>
    <a href="{% url 'khata:delete_account' pk=account_pk %}" class="btn btn-outline-danger">Delete Transaction</a>
    </div>
</form>

{% if form.errors %}
    {% for error in form %}
        {% for err in error.errors %}
            <div class="alert alert-danger">
                <strong>{{ err|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

{% endblock %}