Khata_Register/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='khata')),
    path('users/',include('user_app.urls')),
    path('',include('customer_app.urls',namespace='customer')),
    path('about/',views.about,name='about'),
    path('previous_url',views.previous_url,name='previous_url'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
app_name = 'khata'
urlpatterns = [
    path('<int:id>/<str:name>/',views.show_account,name='account'),
    path('gave/',views.Gave.as_view(),name='gave'),
    path('update_gave/<int:pk>/<int:cust_id>/',views.Update_Gave.as_view(),name='update_gave'),
    path('got/',views.Got.as_view(),name='got'),
    path('update_got/<int:pk>/<int:cust_id>/',views.Update_Got.as_view(),name='update_got'),
    path('delete_account/<int:pk>/',views.Delete_Account.as_view(),name='delete_account'),

]

customer_app/urls.py
from django.urls import path
from . import views
app_name = 'customer'
urlpatterns = [
    path('',views.show_customer,name='show_customer'),
    path('<int:id>/',views.show_customer,name='show_customer'),
    path('add_customer/',views.Add_Customer.as_view(),name='add_customer'),
    path('update_customer/<int:pk>/',views.Update_Customer.as_view(),name='update_customer'),
    path('delete_customer/<int:pk>/',views.Delete_Customer.as_view(),name='delete_customer'),
]

templates/customer/add_customer.html
{% extends 'layout_app.html' %}
{% block content %}
{% load static %}
<!doctype html>
<html lang="en">
<html>

<head>
    <link rel="stylesheet" href="{% static 'css/style_customer.css' %}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border border-info rounded-right">
        <h4>
            <a href="{% url 'customer:show_customer' %}" class="btn btn-outline-secondary">
                << </a>
                    <label style="color: blanchedalmond;">Add Customer</label>
        </h4>
    </nav>
    <!-- Navbar ends -->
    <br><br>
    <form class="form-row" method="POST">
        {% csrf_token %}
        <div align="center" class="col-md-4 order-md-1">
            Customer Name: {{form.name}}<br>
            Customer Contact: {{form.contact}}<br>
            <input type="submit" value="Add" class="btn btn-outline-success">
        </div>
    </form>
    <hr>

    {% if form.errors %}
    {% for error in form %}
    {% for err in error.errors %}
    <div class="alert alert-danger">
        <strong>{{ err|escape }}</strong>
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
    {% endif %}
    {% endblock %}

templates/customer/show_customer.html
{% extends 'layout.html' %}
{% block content %}
{% load mathfilters %}


{% if total_balance > 0  %}
<div class="row mb-4" align="center">
  <div class="col-6 themed-grid-col" style="color: green;border:solid;">{{total_balance}}<br><small>You will
      receive</small></div>
  <div class="col-6 themed-grid-col" style="color: red;border:solid;">0<br><small>You will pay</small></div>
</div>
{% elif total_balance == 0 %}
<div class="row mb-4" align="center">
  <div class="col-6 themed-grid-col" style="color: green;border:solid;">0<br><small>You will receive</small></div>
  <div class="col-6 themed-grid-col" style="color: red;border:solid;">0<br><small>You will pay</small></div>
</div>
{% else %}
<div class="row mb-4" align="center">
  <div class="col-6 themed-grid-col" style="color: green;border:solid;">0<br><small>You will receive</small></div>
  <div class="col-6 themed-grid-col" style="color: red;border:solid;">{{total_balance | abs}}<br><small>You will
      pay</small></div>
</div>
{% endif %}

{% for cust in customer %}


<div style="padding: 10px;" class="media text-muted pt-3">
  <svg class="bd-placeholder-img mr-2 rounded" width="40" height="40" xmlns="http://www.w3.org/2000/svg"
    preserveAspectRatio="xMidYMid slice" focusable="false" role="img">
    <title>Placeholder</title>
    <rect width="100%" height="100%" fill="#007bff" /><text x="50%" fill="white" y="50%"
      dy=".3em">{{cust.name | slice:"0:1"}}</text>
  </svg>
  <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
    <strong class="d-block text-gray-dark"><a
        href="{% url 'khata:account' id=cust.id name=cust.name %}">{{cust.name}}</a></strong>
        {% if cust.bal_amount > 0 %}
        <p style="color: green;">{{ cust.bal_amount }}</p>
        {% else %}
        <p style="color: red;">{{ cust.bal_amount | abs }}</p>
        {% endif %}
  </p>
</div>
{% endfor %}
<hr>


<br><br>
<div style="position: fixed;bottom: 0;width: 100%;">
  <label></label>
  <a href="{% url 'customer:add_customer' %}" class="btn btn-outline-primary">Add Customer</a>
</div>

{% endblock %}

templates/customer/update_customer.html
{% extends 'layout_app.html' %}
{% block content %}
{% load static %}
<!doctype html>
<html lang="en">
<html>

<head>
    <link rel="stylesheet" href="{% static 'css/style_customer.css' %}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border border-info rounded-right">
        <h4>
            <a href="{{previous_url}}" class="btn btn-secondary">
                << </a>
                    <label style="color: blanchedalmond;">Update Customer</label>
        </h4>
    </nav>
    <!-- Navbar ends -->
    <br><br>
    <form class="form-row" method="POST">
        {% csrf_token %}
        <div align="center" class="col-md-4 order-md-1">
            <label>Customer Name:</label> {{form.name}}<br>
            <label>Customer Contact:</label> {{form.contact}}<br>
            <input type="submit" value="Update" class="btn btn-outline-success">
            <a href="{% url 'customer:delete_customer' pk=cust_pk %}" class="btn btn-outline-danger">Delete</a>
            

        </div>
    </form>

    {% if form.errors %}
    {% for error in form %}
    {% for err in error.errors %}
    <div class="alert alert-danger">
        <strong>{{ err|escape }}</strong>
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
    {% endif %}
</body>

</html>
{% endblock %}